#!/bin/sh
 
mutex=$(semC 1)    # Création du sémaphore d'exclusion mutuelle avec initialisation
             # de sa valeur à 1. L'identificateur du sémaphore est mémorisé
             # dans la variable mutex.
echo "Création du sémaphore d'exclusion mutuelle (id=$mutex)"
for i in 1 2 3; do    # création de trois processus client
   ./mutex-client $mutex $i & # chaque processus client reçoit en argument:
                      # - l'identificateur du sémaphore d'exclusion mutuelle
                      # - son numéro
done
wait          # Attente de la fin des processus clients
semD $mutex           # # Suppression du sémaphore d'exclusion mutuelle
echo "Suppression du sémaphore d'exclusion mutuelle (id=$mutex)"